### ISSUE TITLE
Devourer of Gods' Healthbar doesn't display it's current health

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#13]
The Devourer of Gods' healthbar doesn't show what value it's health is actually at. The problem isn't the health mechanic not working, it's just the healthbar not moving when the health changes.

**Comment by Nolan-OC** [comment]
Hello!

The issue seems to be that there is no audio source attached to the Devourer of Gods.

On line 96 of NPC.cs you have 
`                if (HitSound != null)
                    audioSource.Play();`

The devourer has a HitSound so it passes the check, but it doesnt have an audio source. This throws an error and prevents the healthbar being set properly. When you comment out the audioSource.Play() the healthbar works as intended.

**Comment by Brim7Premium** [comment]
This might have been the case before, but that line doesn’t exist in the NPC script now and the bug still occurs.

**Comment by Nolan-OC** [comment]
I'm not sure how to help then. It is definitely working on my forked version. The player only does 1 damage so it's hard to notice but it's working. That would be a good starting point for this bug

**Comment by Brim7Premium** [comment]
That’s because the change was made on my branch, not main. Once I re-implement the damage system I’ll look out for what you said. Thanks!

**Comment by Best-JelloBeanz** [comment]
Do we still need this issue to be open?

**Comment by Brim7Premium** [comment]
No, even if the problem is still there (which I don't think it is) the DoG doesn't matter to the RoY demo
