### ISSUE TITLE
Velocity System

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#58]
So, In the past we had a velocity system borrowed from terraria that looked like this:
public void UpdateVelocity() => transform.position += (Vector3)velocity;
But then it was replaced by a new one made by @psychoFungus :
    public void UpdateVelocity(){
        if(indulgencesHolders.Contains(NPCName))
            transform.position += (Vector3)velocity;
        else Debug.LogWarning(NPCName + ": Use Rigidbody2D instead of UpdateVelocity");

    }
I honestly have know Idea what either of these systems do/did, and would like an explanation. The old system seemed to work fine, and the new system seems to be more limited (at least on slimes)
What I'm suggesting is some form of a new velocity system, but I don't really know what we need for that because I don't quite understand the previous/current ones.

**Comment by psychoFungus** [comment]
Previous system changed position of NPC directly, which is very likely to cause some issues with clipping in the future. I thought that using dynamic rigidbody was better. I changed the function so that only existing enemies could use it. Current system is very flexible and can be changed in some way if you want.

**Comment by Brim7Premium** [comment]
I guess I just need a more thorough explanation of why we need to modify the base methods of movement in the first place

**Comment by psychoFungus** [comment]
Moving anything by directly changing its position will result in clipping into colliders. For flat surfaces like wall, this can be fixed through raycast, but for more complex ones I need to write some tricky recursive algorithm, which already has implementation in built-in rigidbody physics. Currently this isn't very noticable because vertical movement is managed by other systems, but just place wall and slime behind it and you'll see what I mean. Devourer can be left without big changes, but other ones need to be remade.
